### ISSUE TITLE
Sim can crash when taking screenshots

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/function-builder#150] opened 2022-06-09 16:17 UTC
For https://github.com/phetsims/qa/issues/804 and https://github.com/phetsims/qa/issues/805.

This is a general issue, see https://github.com/phetsims/scenery/issues/1424.  Blocking and on-hold until that issue is addressed.

**Comment by pixelzoom** [comment] 2022-06-10 21:21
In the above commits, I patched scenery branches function-builder-1.2 and function-builder-basics-1.2. 

shas that were cherry-picked:

https://github.com/phetsims/scenery/commit/e761ef4da06cc8c4e1a5c0578d68d0db5b34a4ad
https://github.com/phetsims/scenery/commit/ace23fc4566773387bb33efa9960b4248b702f5f

**Comment by pixelzoom** [comment] 2022-06-10 21:41
To verify in 1.2.0-rc.2:

* Test on iPad to verify that it's still fixed.
* Test on a few desktop platforms (macOS and Win) to verify that it's working correctly there too.

History for the general issues is in https://github.com/phetsims/scenery/issues/1424.

**Comment by KatieWoe** [comment] 2022-06-13 19:18
I was unable to reproduce this in RC 2. Closing

**Closed by KatieWoe** 2022-06-13 19:18 UTC
Labels: status:ready-for-review, status:blocks-sim-publication
