### ISSUE TITLE
[Edge] Input carousel doesn't clip to current page of items

### ISSUE THREAD

**Issue by phet-steele** [phetsims/function-builder#32] opened 2016-05-11 16:49 UTC
@pixelzoom Edge only problem seen during phetsims/tasks/issues/589, and give this a better title :smile:.

The next "set" of cards are seen prematurely in the input carousel. This occurs immediately upon sim load and happens in each screen. The cards are not interactable and do not prevent the use of the checkbox options. This does not occur in the output carousel.
![edgecards](https://cloud.githubusercontent.com/assets/5863899/15189002/bbcc9730-1765-11e6-9437-66ff0e9eff15.PNG)

Troubleshooting information:
Name: ‪Function Builder‬
URL: http://www.colorado.edu/physics/phet/dev/html/function-builder/1.0.0-dev.25/function-builder_en.html
Version: 1.0.0-dev.25 2016-05-05 18:36:48 UTC
Features missing: touch
Flags: pointerEnabled
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36 Edge/12.10240
Language: en-US
Window: 1600x746
Pixel Ratio: 1/1
WebGL: WebGL 0.95
GLSL: WebGL GLSL ES 0.95
Vendor: Microsoft (Internet Explorer)
Vertex: attribs: 16 varying: 15 uniform: 512
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"7d27130a","branch":"master"},"axon":{"sha":"5e33541f","branch":"master"},"babel":{"sha":"b461c809","branch":"master"},"brand":{"sha":"bb1cfcc6","branch":"master"},"chipper":{"sha":"184674ba","branch":"master"},"dot":{"sha":"04efe0bc","branch":"master"},"function-builder":{"sha":"3d4fe673","branch":"master"},"joist":{"sha":"48836bcf","branch":"master"},"kite":{"sha":"dce9765e","branch":"master"},"phet-core":{"sha":"c48bf320","branch":"master"},"phetcommon":{"sha":"eab7fb7f","branch":"master"},"scenery":{"sha":"7590be09","branch":"master"},"scenery-phet":{"sha":"436bf61d","branch":"master"},"sherpa":{"sha":"ab4d5c14","branch":"master"},"sun":{"sha":"9f2d40d5","branch":"master"},"tandem":{"sha":"5af5b8f8","branch":"master"},"twixt":{"sha":"53b31872","branch":"master"}}

**Comment by phet-steele** [comment] 2016-05-11 17:00
Scrolling through the carousel shows previous cards above as well. Numbers screen on startup also shows previous cards:

![edgecardsnum](https://cloud.githubusercontent.com/assets/5863899/15189378/9a14b4b8-1767-11e6-85e4-3e5544fdefa8.PNG)

**Comment by pixelzoom** [comment] 2016-05-11 17:02
A carousel clips the set of items that it contains, so that the current "page" of items is shown. In the first screenshot above (Patterns carousel), you're seeing the next page of items below the carousel. In the second screenshot above you're seeing both the next page (below the carousel) and previous page (above the carousel).  So there is a serious clipping issue here.  Since this sim relies heavily on scenery's clipArea feature, this is concerning.  It's obviously a showstopper, and I have no idea how to address it.

Assigning to @ariel-phet to prioritize and assign.

**Comment by pixelzoom** [comment] 2016-05-11 17:02
Btw... sun.Carousel is a common UI component, so I suspect that this affects any sim that uses a Carousel.

**Comment by phet-steele** [comment] 2016-05-11 17:06
> Btw... sun.Carousel is a common UI component, so I suspect that this affects any sim that uses a Carousel.

Area Builder and even the Sun Demo sim do not have this issue.

**Comment by pixelzoom** [comment] 2016-05-11 17:10
Mentioning @jonathanolson, since he will undoubtedly be involved in addressing this.

**Comment by ariel-phet** [comment] 2016-05-11 18:52
@pixelzoom since area builder and Sun Demo do not have this issue can you investigate if there are any differences in the function builder implementation?

**Comment by pixelzoom** [comment] 2016-05-11 19:11
I do not have an Edge test platform, so I cannot confirm whether this is an issue with other sims that use Carousel.  That said...

I don't believe that this issue is with how function-builder is using Carousel. It is not customizing Carousel, or doing anything unusual with it.  I suspect that this issue (as well as #33 and #35) are caused by function-builder's heavy reliance on multiple clipAreas.  In the "Equations" screen alone, there are 8 clipAreas -- 3 in carousels, 3 in drawers (soon to be 4, because the table requires an additional clipArea for scrolling), 1 for making cards appear to enter/exit the builder through input/output slots, 1 for 'see inside' windows in builder.

**Comment by ariel-phet** [comment] 2016-05-11 19:51
@pixelzoom thanks for the clarification

Assigning to @jonathanolson since likely related to clipAreas in Edge

**Comment by pixelzoom** [comment] 2016-05-12 18:46
At 5/12/16 dev meeting, @ariel-phet said that iOS issues are higher priority than Edge issues, so lowering the priority of this from "top" to "high".

**Comment by pixelzoom** [comment] 2016-06-02 15:44
@jonathanolson status?

**Comment by jonathanolson** [comment] 2016-06-02 16:42
Should be fixed by https://github.com/phetsims/scenery/issues/518, which is at the top of my list (and I'm working on it).

**Comment by pixelzoom** [comment] 2016-06-07 03:14
In Skype, @jonathanolson said:

[6/6/16, 9:10:43 PM] Jonathan Olson: The backup would presumably be to try SVG out on Edge
[6/6/16, 9:10:57 PM] Jonathan Olson: That's one thing we could try now (see how ?rootRenderer=svg works on Edge)

**Comment by jonathanolson** [comment] 2016-06-09 06:54
Latest Scenery commit (https://github.com/phetsims/scenery/commit/768bf4537826a6bbda1ad6fc548883bc8b905179) appears to fix this. @phet-steele, can you verify?

**Comment by phet-steele** [comment] 2016-06-09 15:08
@jonathanolson verified fixed on the original device.

**Comment by pixelzoom** [comment] 2016-06-09 21:07
I don't have an Edge test platform, and don't have time to set one up.  So I'll take @phet-steele's word for it and close this issue.

**Closed by pixelzoom** 2016-06-09 21:07 UTC
Labels: priority:2-high, status:fixed-pending-testing, type:bug
