### ISSUE TITLE
[Safari] MathSymbolFont leaves graphics artifact on Equations screen

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/function-builder#145] opened 2022-05-20 01:40 UTC
**Test device**
MacBook Air (m1 chip)

**Operating System**
12.3.1

**Browser**
safari

**Problem description**
For https://github.com/phetsims/qa/issues/804, I see a very minor artifact on the Equations Screen -- when the 'y' in the equation moves to the right, the end of the tail stays behind. (Sorry-I know these artifact issues are annoying)

* This is also seen in published
* This doesn't happen in chrome. 

**Steps to reproduce**
There are many ways to reproduce. Here is one:
1. On the Equations Screen, add the functions in the following order: +2, x2, /2
2. Open the bottom tab to see the equation
3. Check the simplify checkbox

**Visuals**

https://user-images.githubusercontent.com/87318828/169431167-2f7b5eee-28b6-4a89-aa4c-ff050a5afe53.mp4

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Function Builder‬
URL: https://phet-dev.colorado.edu/html/function-builder/1.2.0-dev.7/phet/xhtml/function-builder_all.xhtml
Version: 1.2.0-dev.7 2022-05-19 15:05:31 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.4 Safari/605.1.15
Language: en-US
Window: 1209x706
Pixel Ratio: 2/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0 (1.0)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 256
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by pixelzoom** [comment] 2022-05-20 15:22
Reproduced in master.

This problem occurs when `MathSymbolFont` is used.  Scenery is getting the bounds wrong, and therefore leaving graphics artifacts when the rendered equation changes.  To confirm, make this change in FBConstants.js. You'll see that there is no problem when using `PhetFont`.

```diff
-    xyFont: new MathSymbolFont( 30 ), // {Font} font for x & y symbols
+    xyFont: new PhetFont( 30 ), // {Font} font for x & y symbols
```

Using `?renderer=canvas` results in no change. 

My recommendation is to:
* open a general scenery issue to have @jonathanolson investigate the bounds problem with MathSymbolFont
* close this as "won't fix" for Function Builder 1.2 release

@amanda-phet do you agree?

**Comment by jonathanolson** [comment] 2022-05-25 14:53
> Using ?renderer=canvas results in no change.

Using `?rootRenderer=canvas` fixes this. But it's worth a try, it slaughters the sim's performance (looks like due to the filters, Safari + Canvas has to use a particularly slow code-path for filters).

**Comment by jonathanolson** [comment] 2022-05-25 14:54
Since this looks like an SVG issue, there's the usual workaround attempt of "put some `fill: 'transparent'` rectangle around it that somehow forces a repaint in SVG" solution. Let me know if collaborating would be good.

**Comment by pixelzoom** [comment] 2022-05-25 16:51
I'm really not excited about the recommended workaround. Especially since this is a general problem with MathSymbolFont that affects all sims that use it.  I've created https://github.com/phetsims/scenery/issues/1416 to address the general problem.

In the meantime, I recommend that we "do nothing" for Function Builder, and live with the artifacts. @amanda-phet do you agree?

**Comment by amanda-phet** [comment] 2022-05-25 18:40
This was first documented last year in https://github.com/phetsims/scenery-phet/issues/689 

My recommendation continues to be that we don't address it until @kathy-phet prioritizes it. 

@pixelzoom do you have a recommendation for which issue we keep for tracking the discussion/fix for this? https://github.com/phetsims/scenery-phet/issues/689 or https://github.com/phetsims/scenery/issues/1416?

**Comment by pixelzoom** [comment] 2022-05-25 19:12
I closed duplicate https://github.com/phetsims/scenery/issues/1416, and moved the info to https://github.com/phetsims/scenery-phet/issues/689.

Closing this issue as "won't fix".

**Closed by pixelzoom** 2022-05-25 19:12 UTC
Labels: type:bug
