### ISSUE TITLE
Mystery screen takes longer to enter

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/function-builder#143] opened 2022-02-09 20:11 UTC
**Test device**
iPad
**Operating System**
iPadOS 15.3
**Browser**
Safari
**Problem description**
For https://github.com/phetsims/qa/issues/766. Fairly minor, and I didn't see it on my Windows 11 device.
When switching screens, the mystery screen was noticeably slower to be entered than the others. This was on iPad, though a newer iPad. Not sure if it was slow enough to be considered a problem. It also didn't seem to happen in the published sim. Even in the dev version with the iPad it was sometimes inconsistent.

**Visuals**

https://user-images.githubusercontent.com/41024075/153281651-e184c38b-8312-4169-a78c-e177c38c992b.MP4

**Comment by pixelzoom** [comment] 2022-02-09 20:31
I've tested 1.2.0-dev.6 this with an iPad 6, iPhone 11, and MacBook Pro.  I can't reproduce this - switching to the Mystery screen was just as fast as any of the other screens.  So I suspect this is a problem with the test device. 

@KatieWoe Did you try rebooting the iPad? Could you try on a different iPad?

**Comment by KatieWoe** [comment] 2022-02-09 20:46
Rebooting the iPad did not fix this. I tested on an iPhone 7 and while I could see it there, it seemed much less noticeable.

**Comment by amanda-phet** [comment] 2022-02-10 20:43
I'm not sure what to do for this, either. I just tested on my iPad 6 (iOS 14) and couldn't reproduce it, so there's probably not much we can do unless it's more pervasive. 

Assigning to @kathy-phet to prioritize.

**Comment by pixelzoom** [comment] 2022-02-16 23:00
@kathy-phet waiting for you to prioritize and decide whether this is blocking.

**Comment by pixelzoom** [comment] 2022-02-16 23:01
Labeling as blocking until I hear otherwise.

**Comment by pixelzoom** [comment] 2022-02-17 20:46
2/17/22 design meeting:

@kathy-phet says does not block publication, and is not worth investigating in Function Builder. @KatieWoe if QA sees this pattern in other sims, please bring it up again.

Closing.

**Closed by pixelzoom** 2022-02-17 20:46 UTC
Labels: type:performance, status:blocks-sim-publication
