### ISSUE TITLE
Automated Testing Errors

### ISSUE THREAD

**Issue by phet-steele** [phetsims/function-builder#16] opened 2016-03-17 19:26 UTC
fuzztesting build, on phettest:
```
Uncaught TypeError: Cannot read property 'addRemoveCounter' of null
TypeError: Cannot read property 'addRemoveCounter' of null
    at e.i.onChildRemoved (http://phettest.colorado.edu/function-builder/build/function-builder_en.html?ea&postMessageOnLoad&postMessageOnError&fuzzMouse=100:572:18065)
    at r.e.trigger2 (http://phettest.colorado.edu/function-builder/build/function-builder_en.html?ea&postMessageOnLoad&postMessageOnError&fuzzMouse=100:562:6822)
    at r.o.removeChildWithIndex (http://phettest.colorado.edu/function-builder/build/function-builder_en.html?ea&postMessageOnLoad&postMessageOnError&fuzzMouse=100:568:6)
    at r.o.removeChild (http://phettest.colorado.edu/function-builder/build/function-builder_en.html?ea&postMessageOnLoad&postMessageOnError&fuzzMouse=100:567:31460)
    at Object.c.endDrag (http://phettest.colorado.edu/function-builder/build/function-builder_en.html?ea&postMessageOnLoad&postMessageOnError&fuzzMouse=100:583:22083)
    at addInputListener.s.end (http://phettest.colorado.edu/function-builder/build/function-builder_en.html?ea&postMessageOnLoad&postMessageOnError&fuzzMouse=100:581:27658)
    at e.i.endDrag (http://phettest.colorado.edu/function-builder/build/function-builder_en.html?ea&postMessageOnLoad&postMessageOnError&fuzzMouse=100:581:26459)
    at Object.dragListener.up (http://phettest.colorado.edu/function-builder/build/function-builder_en.html?ea&postMessageOnLoad&postMessageOnError&fuzzMouse=100:581:25071)
    at e.i.dispatchToPointer (http://phettest.colorado.edu/function-builder/build/function-builder_en.html?ea&postMessageOnLoad&postMessageOnError&fuzzMouse=100:573:23710)
    at e.i.dispatchEvent (http://phettest.colorado.edu/function-builder/build/function-builder_en.html?ea&postMessageOnLoad&postMessageOnError&fuzzMouse=100:573:23441)
```

**Comment by phet-steele** [comment] 2016-03-17 19:34
fuzztesting requirejs:
```
assert.js:23 Uncaught Error: Assertion failed: nodes in animationLayer should not be pickable
window.assertions.assertFunction @ assert.js:23
CardNode.options.startDrag @ CardNode.js?bust=1458242805484:71
MovableNode.addInputListener.SimpleDragHandler.start @ MovableNode.js?bust=1458242805484:56
inherit.startDrag @ SimpleDragHandler.js?bust=1458242805484:153
inherit.tryToSnag @ SimpleDragHandler.js?bust=1458242805484:180
inherit.down @ SimpleDragHandler.js?bust=1458242805484:197
inherit.dispatchToTargets @ Input.js?bust=1458242805484:846
inherit.dispatchEvent @ Input.js?bust=1458242805484:788
inherit.downEvent @ Input.js?bust=1458242805484:672
inherit.mouseDown @ Input.js?bust=1458242805484:315
extend.fuzzMouseEvents @ Display.js?bust=1458242805484:1095
inherit.stepSimulation @ Sim.js?bust=1458242805484:683
inherit.runAnimationLoop @ Sim.js?bust=1458242805484:657
```

**Comment by phet-steele** [comment] 2016-03-17 19:37
fuzztesting requirejs, in Chrome:
```
assert.js:23 Uncaught Error: Assertion failed: Attempted to removeChild with a node that was not a child.
window.assertions.assertFunction @ assert.js:23
extend.removeChild @ Node.js?bust=1458242805484:382
CardNode.options.endDrag @ CardNode.js?bust=1458242805484:140
MovableNode.addInputListener.SimpleDragHandler.end @ MovableNode.js?bust=1458242805484:68
inherit.endDrag @ SimpleDragHandler.js?bust=1458242805484:165
SimpleDragHandler.dragListener.up @ SimpleDragHandler.js?bust=1458242805484:74
inherit.dispatchToPointer @ Input.js?bust=1458242805484:811
inherit.dispatchEvent @ Input.js?bust=1458242805484:784
inherit.upEvent @ Input.js?bust=1458242805484:654
inherit.mouseUp @ Input.js?bust=1458242805484:326
extend.fuzzMouseEvents @ Display.js?bust=1458242805484:1091
inherit.stepSimulation @ Sim.js?bust=1458242805484:683
inherit.runAnimationLoop @ Sim.js?bust=1458242805484:657
```

**Comment by phet-steele** [comment] 2016-03-17 19:38
fuzztesting requirejs, in Chrome:
```
assert.js:23 Uncaught Error: Assertion failed: slot 2 is occupied
window.assertions.assertFunction @ assert.js:23
inherit.addFunctionNode @ BuilderNode.js?bust=1458242805484:177
(anonymous function) @ FunctionNode.js?bust=1458242805484:132
inherit.step @ Movable.js?bust=1458242805484:99
inherit.step @ PatternsScene.js?bust=1458242805484:129
inherit.step @ PatternsModel.js?bust=1458242805484:78
inherit.stepSimulation @ Sim.js?bust=1458242805484:719
inherit.runAnimationLoop @ Sim.js?bust=1458242805484:657
```

**Comment by pixelzoom** [comment] 2016-03-17 19:41
@phet-steele Are all of these tests with master?

**Comment by phet-steele** [comment] 2016-03-17 19:44
All but the first were tested on the version of master at 11:41 AM today, so any commits made since were not taken into account.

**Comment by phet-steele** [comment] 2016-03-17 19:46
Addendum, the first was actually the same time as the others.

**Comment by pixelzoom** [comment] 2016-03-17 19:55
The last 3 are all known issues, marked with TODO items in the source code. I've added this issue number next to those TODO items. 

The first issue (https://github.com/phetsims/function-builder/issues/16#issue-141683887) is not something that I recognize, looks like it's internal to scenery. And the error message doesn't point me to a location in the sim source code.  @jonathanolson Can you provide any hints on where I might look to identify the source of this error?

**Comment by pixelzoom** [comment] 2016-03-17 21:54
Assertions 2 & 3 above come in pairs, so they are likely related.

**Comment by pixelzoom** [comment] 2016-03-17 21:54
In 1 hour of fuzzMouse testing, I have not been able to reproduce assertions 1 & 4.

**Comment by phet-steele** [comment] 2016-03-17 22:00
@pixelzoom I can't say anything about 1, but 4 I've seen twice (once in OSX Safari and once in Win 10 Chrome) taking only a couple of minutes each time. Guess I'm lucky?

**Comment by pixelzoom** [comment] 2016-03-17 22:04
While I haven't seen assertion 4, I believe I know what could cause it.  2 functions may both be competing for the same slot in the builder. The first function sees that the slot is empty, so start animating towards it.  Before the first function arrives and gets put in the slot, a second function notices that the slot is empty, and also starts animating towards it. When the second slot arrives, it finds that the slot is filled, and the assertion fails (e.g. "slot 2 is occupied").   I'll probably have to introduce a field that "reserves" a slot.

**Comment by pixelzoom** [comment] 2016-03-17 22:17
@phet-steele I've reviewed these test results. Since there are 3 different problems here, I've created 3 separate issues (#17, #18, #19).

Closing.

**Closed by pixelzoom** 2016-03-17 22:17 UTC
Labels: type:bug
