### ISSUE TITLE
Clicking on an item or function can cause screen to pan

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/function-builder#142] opened 2022-02-09 16:47 UTC
**Test device**
MacBook Air (m1 chip)

**Operating System**
12.0.1

**Browser**
Safari and Chrome

**Problem description**
For https://github.com/phetsims/qa/issues/766, https://github.com/phetsims/qa/issues/767 and possibly related to https://github.com/phetsims/joist/issues/770:

Sometimes, when I click on an item in the carousel or a function while zoomed in, the screen pans. 

**Steps to reproduce**
1. Go to any screen and zoom in. 
2. Click on an item in either carousel. (it may take a couple of tries for the pan to occur)
OR
1. Add a function to the tunnel 
2. Zoom in and then click on that function.

**Visuals**
![panning](https://user-images.githubusercontent.com/87318828/153248147-ccf78f16-558d-4b8a-898d-78fce58ac84f.gif)

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Function Builder‬
URL: https://phet-dev.colorado.edu/html/function-builder/1.2.0-dev.6/phet/function-builder_all_phet.html
Version: 1.2.0-dev.6 2022-02-08 17:45:56 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.1 Safari/605.1.15
Language: en-US
Window: 1409x687
Pixel Ratio: 2/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0 (1.0)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by pixelzoom** [comment] 2022-02-09 20:42
I reproduced the problem in 12.0-dev.6 and master.  I tried a few other sims that use Carousel, and saw this behavior occassionally, but not a consistently as in Function Builder. Perhaps it's because cards taken from the left carousel are constrained to be dragged on a straight line to the input slot of the "builder"?  

@jessegreenberg any thoughts?

**Comment by jessegreenberg** [comment] 2022-02-10 17:20
I am disappointed with how panning while dragging an object is working currently, it keeps causing problems like this and https://github.com/phetsims/joist/issues/769 and https://github.com/phetsims/molecule-shapes/issues/213. I am meeting with JO this afternoon to discuss the approach and alternatives.

**Comment by pixelzoom** [comment] 2022-02-10 19:01
My feeling is that this should not block forward progress on Function Builder, since any fix will (hopefully?) be addressed as a maintenance release to all sims.  @jessegreenberg @amanda-phet do you agree?

**Comment by amanda-phet** [comment] 2022-02-10 19:25
@pixelzoom I agree, this doesn't need to block Function Builder.

**Comment by jessegreenberg** [comment] 2022-02-10 19:52
So far issues related to this were not important enough to block publication. So I wasn't expecting to do a batch maintenance release, but I will check with @kathy-phet and others about whether that is worthwhile.

This case seems worse than others and I think it should be fixed, but I understand if that doesn't fit in the timeline. Pan and zoom could be disabled for this publication if that is best. https://github.com/phetsims/scenery/issues/1356 might be fixed by Tuesday 2/15/22 depending on what comes out of https://github.com/phetsims/scenery/issues/1356.

**Comment by kathy-phet** [comment] 2022-02-11 00:51
This sim doesn't have a deadline for re-publication, so the timeline is fine and fixing this issue sounds good.

**Comment by jessegreenberg** [comment] 2022-02-16 17:45
This has been fixed in function-builder. The solution in https://github.com/phetsims/scenery/issues/1356 doesn't work in this case yet because of https://github.com/phetsims/scenery/issues/1361 and the usage of DAG in this sim so https://github.com/phetsims/function-builder/commit/8aba031e024896fd4f8d833005ebcf24c3ef4eb2 was added to fix this. That workaround can be removed once https://github.com/phetsims/scenery/issues/1361 is addressed. Reassigning to @pixelzoom if there are any questions or to proceed.

**Comment by pixelzoom** [comment] 2022-02-16 22:58
I'm not familiar with how this feature is implemented, and I don't understand the solution.  So I'll take your word for it.

@Nancy-Salpepi would you please verify that this is fixed in master?

**Comment by Nancy-Salpepi** [comment] 2022-02-17 13:05
@pixelzoom I am no longer able to reproduce cases where significant panning occurs when I click on an item. 

In some cases, if I click on an item that is partially off screen, the screen will pan slightly so that the entire object is on screen. I think this is acceptable behavior, but leaving it up to you as to whether this can be closed or not. 



https://user-images.githubusercontent.com/87318828/154487393-c070cfb5-5278-450a-a7f8-84b448cca794.mp4

**Comment by pixelzoom** [comment] 2022-02-17 16:43
> In some cases, if I click on an item that is partially off screen, the screen will pan slightly so that the entire object is on screen. I think this is acceptable behavior, but leaving it up to you as to whether this can be closed or not.

I don't know know how this feature is supposed to behave. @jessegreenberg is this acceptable behavior?

**Comment by pixelzoom** [comment] 2022-02-17 18:27
Great, thanks.  Then this is ready to rock N roll.  Closing.

**Closed as completed by pixelzoom** 2022-02-17 18:27 UTC
Labels: type:bug, status:ready-for-review, status:blocks-sim-publication
