### ISSUE TITLE
Equations screen slight memory leak

### ISSUE THREAD

**Issue by phet-steele** [phetsims/function-builder#93] opened 2016-07-11 20:12 UTC
@pixelzoom this is an incredibly slow memory leak, but it's a leak nonetheless and it wouldn't feel right not reporting it. It probably isn't an incredibly pressing issue.
I constrained the sim to the Equations screen, ran fuzzMouse, and took a heap snapshot every 5 minutes for an hour with this URL http://www.colorado.edu/physics/phet/dev/html/function-builder/1.0.0-rc.1/function-builder_en.html?fuzzMouse=100&screens=3. I ran similar tests on all other screens, with no apparent leaks. The Patterns and Mystery screens were difficult to test; fuzzMouse would get stuck switching between function machine representations (number of slots). There might have been leaks on those screens, but the tests were generally inconclusive. I ran this in Chrome on OSX 10.11.5 :

| Minutes | MB |
| --- | --- |
| 0 | 28.4 |
| 5 | 29.1 | 
| 10 | 29.9 |
| 15 | 30.7 |
| 20 | 30.8 |
| 25 | 31.0 |
| 30 | 32.0 |
| 35 | 31.9 |
| 40 | 32.6 |
| 45 | 33.1 |
| 50 | 33.9 |
| 55 | 34.3 |
| 60 | 34.6 |

For phetsims/tasks/issues/638.
Troubleshooting information:
Name: ‪Function Builder‬
URL: http://www.colorado.edu/physics/phet/dev/html/function-builder/1.0.0-rc.1/function-builder_en.html
Version: 1.0.0-rc.1 2016-07-11 16:15:00 UTC
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.106 Safari/537.36
Language: en-US
Window: 1536x739
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"7d27130a","branch":"master"},"axon":{"sha":"9a0e2f3a","branch":"master"},"babel":{"sha":"101ec12c","branch":"master"},"brand":{"sha":"f0b1f7da","branch":"master"},"chipper":{"sha":"9059e93b","branch":"master"},"dot":{"sha":"3628c3ae","branch":"master"},"function-builder":{"sha":"7daf67e1","branch":"1.0"},"joist":{"sha":"94bc734c","branch":"master"},"kite":{"sha":"88f0c3a0","branch":"master"},"phet-core":{"sha":"c48bf320","branch":"master"},"phetcommon":{"sha":"35ef94ad","branch":"master"},"scenery":{"sha":"942889ad","branch":"master"},"scenery-phet":{"sha":"0d6b589e","branch":"master"},"sherpa":{"sha":"03590a07","branch":"master"},"sun":{"sha":"cccaf534","branch":"master"},"tandem":{"sha":"a8ac284b","branch":"master"},"twixt":{"sha":"53b31872","branch":"master"}}

**Comment by pixelzoom** [comment] 2016-07-12 15:39
Memory management in this sim is relatively simple. It allocates all of its objects at startup, and all of those objects exist for the lifetime of the sim.  The only thing that's allocated is Vector2 as cards and functions are dragged, and I've verified that those are being disposed of properly (if they weren't, we'd know it pretty quickly).  So I suspect that this leak may be coming from something in common code. 

@phet-steele Do you have any information on what types of objects were on the heap?

**Comment by pixelzoom** [comment] 2016-07-12 15:56
Memory leaks in common-code were investigated (mainly by @jbphet) in https://github.com/phetsims/tasks/issues/546. That issue was closed with the statement that "big memory leaks have been fixed, and we have several tests that demonstrate that there are no major leaks in most sims" (https://github.com/phetsims/tasks/issues/546#issuecomment-218838675).  And amount of memory leaking in Function Builder looks very similar to the profile shown in (for example) https://github.com/phetsims/tasks/issues/546#issuecomment-218002473. 

So this is further evidence for my suspicion that this leak is in common code.

**Comment by pixelzoom** [comment] 2016-07-12 15:57
(1) Memory leaks in common-code were investigated (mainly by @jbphet) in https://github.com/phetsims/tasks/issues/546. That issue was closed with the statement that "big memory leaks have been fixed, and we have several tests that demonstrate that there are no major leaks in most sims" (https://github.com/phetsims/tasks/issues/546#issuecomment-218838675).  So there are undoubtedly small memory leaks in common code that haven't been fixed.

(2) The amount of memory leaking in Function Builder looks very similar to the profile shown in (for example) https://github.com/phetsims/tasks/issues/546#issuecomment-218002473. 

So this is further evidence for my suspicion that this leak is in common code.

**Comment by pixelzoom** [comment] 2016-07-12 17:13
Running with `fuzzMouse=1000&screens=3` over 6 minutes, I reproduced approximately what @phet-steele is seeing - a very slow memory leak.

I asked for a second set of eyes on this, and @samreid obliged. Here's the Skype discussion:

> [7/12/16, 10:51:51 AM] Chris Malley: A very slow memory leak has been reported for Function Builder in https://github.com/phetsims/function-builder/issues/93.  I suspect that it's due to common code, see https://github.com/phetsims/tasks/issues/546#issuecomment-218838675.  Does anyone know what leaks may still be present in joist et. al?  (JB is probably most familiar with this, but he's unlikely to be back before I need to address this.)
[7/12/16, 10:55:11 AM] Sam Reid: That’s a pretty slow leak (perhaps below our threshold of leaks we’ve plugged), but I’m running a fuzz test and will take a look at snapshots to see if anything stands out.
[7/12/16, 10:55:37 AM] Chris Malley: Indeed, quite slow.  Thanks for looking.
[7/12/16, 11:05:48 AM] Chris Malley: Steele's leak testing was done with fuzzMouse=100 over 60 minutes. I'm thinking I should be able to reproduce with fuzzMouse=1000 over 6 minutes.  Anything wrong with that logic?
[7/12/16, 11:06:42 AM] Sam Reid: Yes, that makes the assumption that all allocations are a direct result of mouse events.  Not necessarily true.
[7/12/16, 11:07:10 AM] Chris Malley: Ah, right. But that probably is true in this sim.
[7/12/16, 11:08:02 AM] Sam Reid: Also, I’ve been going at fuzzMouse=1000 for about 6 minutes (give or take a few minutes) and I’ve seen memory grow from 30MB to 32.3MB
[7/12/16, 11:08:31 AM] Chris Malley: I see the approximately the same.  But I don't see anything on the heap that stands out.
[7/12/16, 11:08:44 AM] Sam Reid: Me too, but there is a lot of scenery internal that I don’t understand.
[7/12/16, 11:08:50 AM] Chris Malley: Ditto.
[7/12/16, 11:09:35 AM] Chris Malley: I don't think we should spend much more time on this, diminishing returns. Do you agree? If so, I'll capture this discussion in the issue and move on.
[7/12/16, 11:10:37 AM] Sam Reid: Since the memory leak rate of Function Builder is not appreciably above the memory leak rate of Blast, this is not a blocking issue for publication of the simulation.  Some day it would be nice to dedicate a week or so to understanding and squashing memory leaks, but this Function Builder report doesn’t necessarily mean now is the best time.
[7/12/16, 11:10:55 AM] Chris Malley: Agreed. Moving on :) Thanks for your help.

**Comment by pixelzoom** [comment] 2016-07-12 19:42
My recommendation is to close this at "won't fix", because:

• The leak is very small, 6.2 MB over 60 minutes of fuzz testing, where 100 user interactions are happen per frame. The browser is unlikely to crash under any real usage scenario.

•  Heap comparison indicates no sim-specific objects are leaking. The leak is almost certainly in common code.

• While identifying and fixing common-code leaks is something that should be done, its priority is low, and should not hold up publishing of this sim.

@ariel-phet Do you agree? If so, please close this issue.

**Comment by ariel-phet** [comment] 2016-07-12 21:40
Agreed.

**Closed by ariel-phet** 2016-07-12 21:40 UTC
Labels: type:performance, type:wontfix
