### ISSUE TITLE
star.png off center when rotated

### ISSUE THREAD

**Issue by phet-steele** [phetsims/function-builder#34] opened 2016-05-11 18:07 UTC
The image for star.png could use a redraw or resize. It does not look as expected when rotated 90 degrees (looks off center) maybe due to the image not being perfectly square or the top point being a different size:

![fbstar](https://cloud.githubusercontent.com/assets/5863899/15191169/aa50f2de-1770-11e6-88ae-0982851eb422.PNG)

@pixelzoom please do as you see fit with this info. For phetsims/tasks/issues/589.

**Comment by pixelzoom** [comment] 2016-05-11 18:12
This artwork must be revised. The star is not symmetrical, perhaps it was "eyeballed" when drawn. And the image file is not square; star.png has dimensions 123x120. If the star is to rotate about its center, then the image size must be square, and the center of the star must be in the center of the image file.

Assigning to @ariel-phet to prioritize and assign.

**Comment by pixelzoom** [comment] 2016-05-11 18:14
The asset file for the icons is in GitHub at https://github.com/phetsims/function-builder/blob/master/assets/function-and-card-icons.ai.  Please use this file as a starting point for revising the star, and send me the revised .ai file.

**Comment by ariel-phet** [comment] 2016-05-13 17:35
@amyh-phet this should be a quick fix

**Comment by pixelzoom** [comment] 2016-05-17 16:56
This was likely addressed in https://github.com/phetsims/function-builder/issues/13#issuecomment-219780703. Assigning to myself to verify.

**Comment by pixelzoom** [comment] 2016-05-17 18:11
New icon is now square (123x123), but looks like there's still something weird with the canvas size created by the Rotate90 function, which I'll need to investigate.

**Comment by pixelzoom** [comment] 2016-05-17 20:36
Nothing wrong with the Rotate90 function. The problem is that the star is oddly shaped.   

So when the star is rotated 90 degrees, it looks a little off (as @phet-steele reported).  Here's what it looks like in the output carousel when rotated 90 degree clockwise:

![screenshot_150](https://cloud.githubusercontent.com/assets/3046552/15338297/938abaa0-1c3c-11e6-8b91-59d43c83bf47.png)

Email thread with @amyh-phet:

Me:
> How are you creating this star shape? Free hand?  It's not symmetrical. If a 5-point star is rotated in multiples of 72 degrees (360/5) then the star should look identical in each orientation. This star looks different in each of the 5 multiples of 72 degrees. So when it's rotated by other angles (eg 90) it looks odd. 

@amyh-phet:
> I adjusted the original mock up to have a star with equivalent height and width.  I'm not sure how Amanda created the original artwork, but Illustrator does have a star tool that can be used to make a 5 point star.  My assumption was that she used this tool to make the star. I can create a new star and see if I can create one that is identical in each of the 5 orientations if that would be helpful.

Assigning to @ariel-phet to decide what the goal is here.  If the goal is to have a cartoon star that "wobbles" when it's rotated, then that's what we currently have, and it will continue to look a little "off" when rotated 90 degrees.  If the goal is to

**Comment by ariel-phet** [comment] 2016-05-17 20:47
Will plan on drawing something tonight

**Comment by amyh-phet** [comment] 2016-05-17 20:48
@pixelzoom and @ariel-phet   I'm working on drawing new star now.  Should have it in a few minutes - just need to make sure it is centered on artboard.  I checked rotation in all possible 72 degree increments and shape is identical.

**Comment by ariel-phet** [comment] 2016-05-17 20:54
Or that...thanks @amyh-phet

**Comment by amyh-phet** [comment] 2016-05-17 21:02
@pixelzoom   Can we try this star? 

[star](https://cloud.githubusercontent.com/assets/13650180/15339141/3def0b9c-1c40-11e6-97e6-cb6e992a8c66.png)

Sending AI and png file to you as well.  If this image works, I can update the card-icon Ai file too.

**Comment by pixelzoom** [comment] 2016-05-17 22:25
New star icon integrated, looks like this when rotated 90 degrees:

![screenshot_151](https://cloud.githubusercontent.com/assets/3046552/15341451/f8778128-1c4b-11e6-9598-b4ebe672661c.png)

**Comment by pixelzoom** [comment] 2016-05-17 22:29
I apparently received the wrong card-icons.ai file. Correct file received, integrated again.

**Comment by pixelzoom** [comment] 2016-05-17 23:06
Here's a dev version with the new star card:
http://www.colorado.edu/physics/phet/dev/html/function-builder/1.0.0-dev.29/function-builder_en.html

Assigning to @phet-steele to verify.  In retrospect, the original card was very close to correct.  If you run with `?dev`, a red dot will be placed in the center of each card. This may help you get your bearings.

**Comment by phet-steele** [comment] 2016-05-18 15:15
The rotated star looks equivalent to the above screenshots. The dot show with `?dev` reveals this star is not centered on the card, it's a little low:
![wobblestar](https://cloud.githubusercontent.com/assets/5863899/15364179/c2ab0c12-1cd8-11e6-9f39-f4e8900d32f7.PNG)

**Comment by amyh-phet** [comment] 2016-05-18 15:21
@pixelzoom    

I think the issue had to do with the way Illustrator finds the center of the star.  In order to make a symmetrical star, the height and width of the star are slightly different.  When attempting to align the star using the Align function in AI, the center of the star is determined by finding the center of the bounding box drawn around the star by AI.  This is not actually the center of the star.  If we need to do further adjustments, there is a way to add a point to the exact center of the star.  This point can be manually aligned to the center of an artboard which should allow for 90 and 180 degree rotation without causing a "wobble". The current version of the artwork has the manually added dot at the center of the star.  As you can see in this screenshot, the center of the bounding box is above the center of the star.
![star_center](https://cloud.githubusercontent.com/assets/13650180/15364472/f4605dce-1cd9-11e6-8bbd-fa8e6b674f52.png)


Let me know if you need me to create artwork for the 90 and 180 rotations with the star centered manually.

**Comment by pixelzoom** [comment] 2016-05-18 16:19
We are rotating about the center of the image's bounding box, **not** the object's center of mass.  The triangle shows this more extremely. Here's a screenshot where the black dot indicated the triangle's center:

![screenshot_31](https://cloud.githubusercontent.com/assets/3046552/15366406/655f9876-1ce1-11e6-9bbd-261f74e945d1.png)

For a 5 pointed star, the center of its bounding box is not going to be the same as the center of mass. Since the code has no way of knowing what the image is, there's no way to rotate about some point other than the center.  And we absolutely do not want to use different artwork for different orientations, that defeats the purpose of applying a function.

My feeling is that this is fine as is.  Assigning to @ariel-phet to make an executive decision.

**Comment by ariel-phet** [comment] 2016-05-18 19:48
@pixelzoom if I understand correctly, the star would rotate around its center if the center of the star's bounding box and the center of the star were coincident.

Not saying we go this direction, but as I am chewing on the question, if we used an image such as the one below with a star inscribed in a circle, that would rotate the star about its geometric center correct?

![star](https://cloud.githubusercontent.com/assets/4051174/15372744/2a2ae40e-1cff-11e6-867b-7a2c1ff1285e.PNG)

**Comment by pixelzoom** [comment] 2016-05-18 20:01
Yes, that would work because the geometric center and center of the bounding box are now identical.

**Comment by pixelzoom** [comment] 2016-05-18 20:02
It also looks more like the "Captain America" logo, and that movie is doing gangbusters at the theaters :)

**Comment by ariel-phet** [comment] 2016-05-18 20:17
@pixelzoom I actually had the captain america thought myself. We could even shamelessly go for a red and blue color scheme on it. I will talk to @amyh-phet about a couple of adjustments

**Comment by pixelzoom** [comment] 2016-05-18 21:26
New icon (received from @amyh-phet via email) has been integrated, see:
http://www.colorado.edu/physics/phet/dev/html/function-builder/1.0.0-dev.32/function-builder_en.html

@ariel-phet @amyh-phet @phet-steele please review.

**Comment by ariel-phet** [comment] 2016-05-18 21:28
Looks awesometastic to me

**Comment by pixelzoom** [comment] 2016-05-18 21:31
There's still a problem... I can see the antialiasing on the circle cause it to move when rotation is applied. The circle should be unchanged. Back to the drawing board.

**Comment by pixelzoom** [comment] 2016-05-18 21:38
OK, here's a dev version where the circle stays stationary when the card is rotated:
http://www.colorado.edu/physics/phet/dev/html/function-builder/1.0.0-dev.33/function-builder_en.html

**Comment by amyh-phet** [comment] 2016-05-18 21:39
@pixelzoom   dev 33 looks good.  I don't see any circle movement on this version.

**Comment by ariel-phet** [comment] 2016-05-19 03:50
@pixelzoom I went ahead and made an adjustment to the triangle so that it also fits within a square bounding box and re-uploaded the .ai file. Mind also putting the new triangle in?

**Comment by pixelzoom** [comment] 2016-05-19 16:09
Revised triangle is integrated in master. @ariel-phet please pull and verify.

**Comment by ariel-phet** [comment] 2016-05-19 16:24
Looks great. Closing.

**Comment by amanda-phet** [comment] 2016-06-08 23:40
I was not aware of this conversation until just now when it was referenced in #63 (not sure why I was never mentioned for input...) but I very strongly dislike the circle around the star. I am positive there is a better solution. It looks very out of sync with the other three cards in the carousel. 

I also think the triangle looked fine before and do not understand the change for that one... it is unclear based on the conversation in this issue.

**Comment by pixelzoom** [comment] 2016-06-08 23:45
> (not sure why I was never mentioned for input...) 

Since you're the lead, I assumed you were watching this repository.  Press the "Watch" button at the top-right corner of this page.  It should look like this:

![screenshot_12](https://cloud.githubusercontent.com/assets/3046552/15914746/be2794d4-2da0-11e6-9322-da624ac1b52b.png)

**Comment by pixelzoom** [comment] 2016-06-08 23:47
@amanda-phet Assigning to you. Feel free to come up with a better solution. Recommend to discuss with @ariel-phet.  I have no time available to revisit this.  If you modify the icon, please do so by modifying https://github.com/phetsims/function-builder/blob/master/assets/card-icons.ai, and checking it into GitHub when you're done.

**Comment by amanda-phet** [comment] 2016-06-09 00:06
While I was on leave I only received emails for issues where I was assigned or mentioned, so that my inbox was not overwhelmed with emails.

**Comment by ariel-phet** [comment] 2016-06-09 00:57
@amanda-phet feel free to change however you like so long as the rotation center of the image matches the geometric center of the object. Everyone in the meeting at the time was fine with this solution, but I am sure everyone would be fine with different artwork. As most of the artwork was your brainchild, I am sure you will have a good idea.

**Comment by pixelzoom** [comment] 2016-06-13 21:21
@amanda-phet I'm not wild about the circle either.  Another way to solve this problem is to give the circle zero opacity in Illustrator.  That will ensure that it helps to properly define the size of the image file, but that it won't actually appear in the image. 

To clarify, it would look like this in Illustrator:

![screenshot_22](https://cloud.githubusercontent.com/assets/3046552/16023483/2f9ce498-317a-11e6-9f1f-e31c35f2d7f3.png)

Doing "Save for Web" in Illustrator, it looks like this (note the space below the start, which corresponds to the circle):

![screenshot_23](https://cloud.githubusercontent.com/assets/3046552/16023512/51f95c74-317a-11e6-8a35-8fb3b862a692.png)

In the input carousel, it looks like this:

![screenshot_24](https://cloud.githubusercontent.com/assets/3046552/16023522/59a41f22-317a-11e6-8edd-c9d8b11be030.png)

Output carousel with "Rotate 90" function:

![screenshot_25](https://cloud.githubusercontent.com/assets/3046552/16023539/6ae1546c-317a-11e6-94f2-33bc1f1caef6.png)

Output carousel with "Rotate 180" function:

![screenshot_26](https://cloud.githubusercontent.com/assets/3046552/16023550/75053de6-317a-11e6-973a-fb5d1358a20b.png)

I'm going to go ahead with this change, and check it into GitHub.

**Comment by ariel-phet** [comment] 2016-06-13 21:30
Ah, nice solution @pixelzoom

**Comment by amanda-phet** [comment] 2016-06-13 21:35
My first thought was to make the circle white so it was "invisible" until I realized it would turn black with the color inversion function and look funny with the warhol function... I'm SO glad that making the circle 0% opaque works for this. 

Thank you!!

**Comment by pixelzoom** [comment] 2016-06-13 21:36
@amanda-phet If you're satisfied with this solution, feel free to close the issue.

**Closed** 2016-06-13 21:37 UTC
Labels: design:artwork
