### ISSUE TITLE
Firefox: number card leaves a graphics artifact in builder

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/function-builder#131] opened 2020-03-16 17:59 UTC
**Test device**
Dell
**Operating System**
Win 10
**Browser**
Firefox
**Problem description**
Found during https://github.com/phetsims/chipper/issues/840, however it happens in both versions and in master. Couldn't seem to reproduce in Chrome or in the published version in Firefox.
When sending things through the function machine, sometimes a bit of the outline of the box will stay behind. This is temporary and goes away on its own. It also seems random, but may increase if things are sent through quickly. Using a longer machine may also help reproduce.

**Visuals**
![leftbehindoutline](https://user-images.githubusercontent.com/41024075/76786590-16d74100-677d-11ea-90c6-8d5cc3f810f5.gif)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Function Builder‬
URL: https://phet-dev.colorado.edu/html/function-builder/1.2.0-dev.4/phet/function-builder_en_phet.html
Version: 1.2.0-dev.4 2020-01-23 23:57:39 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:74.0) Gecko/20100101 Firefox/74.0
Language: en-US
Window: 1536x750
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Mozilla (Mozilla)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by pixelzoom** [comment] 2020-03-16 18:05
@KatieWoe I could probably dig them out of phetsims/chipper#840, but could you please be specific about "both versions" in this issue?

**Comment by KatieWoe** [comment] 2020-03-16 18:07
https://phet-dev.colorado.edu/html/function-builder/1.2.0-dev.1/phet/function-builder_en_phet.html
and
https://phet-dev.colorado.edu/html/function-builder/1.2.0-dev.4/phet/function-builder_en_phet.html
First has mipmaps, second doesn't.

**Comment by pixelzoom** [comment] 2020-03-16 18:22
I asked @KatieWoe for clarification of FF version on Slack. She was testing with FF 74.0.  I had FF 73.0.1 installed on macOS 10.15.3, so tested with that first and could not reproduce. After upgrading to FF 74.0 (latest), I can reproduce on macOS.    So this issue appears to have been introduced in FF 74.

That said... This issue is barely noticeable and doesn't impact usability of the sim.  I'll leave it open to see if it goes away in a future version of FF.  But I recommend that we eventually close as "won't fix".

**Comment by pixelzoom** [comment] 2020-03-16 18:23
I'm also removing the bug label.  This is not a bug, it's a rendering artifact that we currently have no control over.

**Comment by pixelzoom** [comment] 2021-05-13 21:36
This is no longer a problem in FF 88.0.1.  Tested on macOS.

Closing.

**Closed by pixelzoom** 2021-05-13 21:36 UTC
Labels: priority:5-deferred
