### ISSUE TITLE
Releasing a card directly centered in a window will let it move back through a non-invertible function

### ISSUE THREAD

**Issue by phet-steele** [phetsims/function-builder#107] opened 2017-04-20 20:22 UTC
As a continuation of #39, there is yet another way to inversely pass cards through a non-invertible function. @pixelzoom this affects function-builder-basics and the current production version of function-builder (1.0.3).

This procedure requires pixel perfect technique. The end goal will be to release a card in the same spot as the resting position of the see inside box.

Example procedure, there might be ways to ignore certain steps and still perform the bug:

1. Place a non-invertible function in a machine and enable the "see inside" checkbox.
2. Drag a card through and let it rest in the see inside window directly after the non-invertible function.
3. Now the tricky, pixel-perfect part. You need to drag and release a card that satisfies two things:
    - The card is released EXACTLY in the same position where it would otherwise rest inside the window
    - The card must be released only after it had just moved LEFT

    The easiest way to accomplish this from step two is to first move the card X amount of pixels to the right, then X amount of pixels to the left. This will guarantee that you have released the card at the same position it started (at rest in the window) and that the card is moving left.

@pixelzoom, here is a video where I've "zoomed" in on the "pixels" (😉) to make it very clear. I've moved one pixel to the right, then one back to the left, then released.
![fb02](https://cloud.githubusercontent.com/assets/5863899/25250622/96898bea-25d3-11e7-9fca-53cf2b4c99cc.gif)

BTW, I'm not convinced this bug can happen if the card does not start in the see inside window, i.e I don't think starting in the output carousel and dragging left will work.

Seen on macOS 10.12.4 Chrome. For phetsims/tasks/issues/823.
URL: http://www.colorado.edu/physics/phet/dev/html/function-builder-basics/1.0.0-dev.3/function-builder-basics_en.html
Version: 1.0.0-dev.3 2017-04-18 15:39:14 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36
Language: en-US
Window: 1920x1014
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 32 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"5c3f9204","branch":"master"},"axon":{"sha":"00436448","branch":"master"},"babel":{"sha":"7840c860","branch":"master"},"brand":{"sha":"a4d6573f","branch":"master"},"chipper":{"sha":"628cdd7d","branch":"master"},"dot":{"sha":"f56a4411","branch":"master"},"function-builder":{"sha":"29939b75","branch":"master"},"function-builder-basics":{"sha":"c49121d8","branch":"master"},"joist":{"sha":"deef1bf3","branch":"master"},"kite":{"sha":"2d9c9d84","branch":"master"},"phet-core":{"sha":"76ec0204","branch":"master"},"phetcommon":{"sha":"d0ffe176","branch":"master"},"query-string-machine":{"sha":"e7055778","branch":"master"},"scenery":{"sha":"69953c5c","branch":"master"},"scenery-phet":{"sha":"8707a265","branch":"master"},"sherpa":{"sha":"0e326d54","branch":"master"},"sun":{"sha":"cfea9c5a","branch":"master"},"tandem":{"sha":"30603e66","branch":"master"},"twixt":{"sha":"b1488b51","branch":"master"}}

**Comment by pixelzoom** [comment] 2017-04-21 02:28
I'm happy to report that I apparently have the same pixel-perfect reflexes a @phet-steele  - I was able to reproduce using the (very helpful) steps above.

**Comment by pixelzoom** [comment] 2017-04-21 02:40
In `CardNode.animateRightToLeft`, `windowNumber` is the number of the window in the builder that is to the left of the card's location.  In this scenario, `windowNumber` is `Function.NO_SLOT_NUMBER` (-1), meaning that there is no window to the left of the card's location. That makes sense if the card is exactly centered in the window.  The problem then is that instead of blocking the card, the card animated back to the input carousel (line 424).

**Comment by pixelzoom** [comment] 2017-04-21 02:49
@phet-steele Your description of the problem made this very easy to locate, and it was trivial to fix. Please test in master.

**Comment by phet-steele** [comment] 2017-04-21 16:36
@pixelzoom I can no longer click a card in a window to have it progress to the next window. I have to give a card a slight nudge to make it move one way or another. Is this functionality important to keep? Otherwise, I can't invert the cards anymore 👍.

**Comment by pixelzoom** [comment] 2017-04-21 18:16
Yes, that's an important feature to keep, thanks for noticing.  Fixed in above commit. Back to you @phet-steele.

**Comment by phet-steele** [comment] 2017-04-21 18:25
@pixelzoom, maestoso!

**Comment by pixelzoom** [comment] 2017-04-21 18:34
Reopening.  Since there are no immediate plans to re-publish Function Builder, I should patch this fix into a 1.0.x maintenance release.

**Comment by pixelzoom** [comment] 2017-04-21 18:51
Patched and deployed in 1.0.4.
https://phet.colorado.edu/sims/html/function-builder/latest/function-builder_en.html

Closing.

**Comment by phet-steele** [comment] 2017-04-21 20:54
@pixelzoom sorry, I take back my "maestoso!". Somewhere in your fixes we lost the ability to easily move cards through the machine in reverse (dragging manually still works, but "flinging" doesn't). Cards get stuck in the machine at window positions (without windows enabled):

![fb03](https://cloud.githubusercontent.com/assets/5863899/25295781/4c838882-26a2-11e7-9a3e-a8b27392b7bd.gif)

**Comment by phet-steele** [comment] 2017-04-21 20:56
Labeled as "top" since it is live on the site.

**Comment by pixelzoom** [comment] 2017-04-23 15:25
Reproduced in 1.0.4 and master.  

So that this isn't "live", I've rolled back the patch in the 1.0 branch, and published 1.0.5.

I'll resume work on the issue in master.

**Comment by pixelzoom** [comment] 2017-04-23 16:07
The other thing we lost here is that, if the card is release exactly centered in the window, it doesn't move to the left and rebound off of the non-invertible function.

**Comment by pixelzoom** [comment] 2017-04-23 16:43
Fixed in above commit. Hopefully third time's the charm.  @phet-steele please give it a workout.

**Comment by pixelzoom** [comment] 2017-04-23 16:44
Fixed in above commit. Hopefully third time's the charm.  

@phet-steele please give it a workout.  If it looks OK, assign back to me for 1.0.6 maintenance release.

**Comment by phet-steele** [comment] 2017-04-25 19:37
I gave it a good look (🤞), but I think another set of eyes would be useful on this. @maggiewiseman can you test this out on function-builder master? Read through this issue to make sure all the cases are accounted for, please.

@pixelzoom I do have one question, above you say:
 
> The other thing we lost here is that, if the card is release exactly centered in the window, it doesn't move to the left and rebound off of the non-invertible function.

This works, releasing a card at the center of the window does make the card bounce off the non-invertible function. But why then does the card do nothing if the function IS invertible? If there is leftward movement after releasing at the center for non-invertible functions, I would expect leftward movement after releasing at the center for invertible functions (or the opposite, where the card does not move in either case). Right?

**Comment by pixelzoom** [comment] 2017-04-25 20:00
@phet-steele and I discussed his above question on the phone.   The scenario in question is when a card is dragged right-to-left, and is released exactly in the center of the "see inside" window.  In that scenario, the behavior depends on whether the function is invertible or non-invertible.  If the function is invertible, then the card stays in the "see inside" window.  If the function is non-invertible, then the card moves left, the "not invertible" sign is displayed, and the card bounces back to the "see inside" window.  This is admittedly a tiny bit inconsistent.  But it's not something that any typical user is going to notice, I don't think it hurts anything, and may even help to reenforce that the function is non-invertible.  And given the risk of making further changes to this particular piece of code, I'm not going to attempt to fix something that isn't really broken.

**Comment by pixelzoom** [comment] 2017-04-25 20:17
@maggiewiseman when you are done with this, please assign the issue back to me so that I can do a maintenance release.

**Comment by maggiewiseman** [comment] 2017-04-26 12:02
Ok! @phet-steele @pixelzoom: Just to be clear, I'm testing function-builder off of master, right?

**Comment by phet-steele** [comment] 2017-04-26 15:29
> Just to be clear, I'm testing function-builder off of master, right?

@maggiewiseman, correct!

**Comment by maggiewiseman** [comment] 2017-04-28 12:46
@pixelzoom @phet-steele  Looks good to me. I cannot make a card get through a non-invertible function and everything seems to be behaving as normal: 
- can still fling right and left (w/ non-invertible function) w/o getting stuck whether there's a function there or not and whether the see-window is on or off.
- click to move to next window works
- a card released in center of window of non-invertible function does bounce back and does show "not invertible" sign.

**Comment by pixelzoom** [comment] 2017-04-28 13:24
Thanks @maggiewiseman, closing.

**Comment by pixelzoom** [comment] 2017-04-28 19:23
This issue was patched in the 1.0 branch (see above commit), and appears in maintenance release 1.0.6.

**Comment by pixelzoom** [comment] 2017-04-28 19:36
Reopening. I just noticed issue https://github.com/phetsims/tasks/issues/690.  Apparently there is a 1.1-phetio branch.  @samreid Does this need to be patched there too?

**Comment by samreid** [comment] 2017-04-28 19:38
The PhET-iO "lite" version of this sim isn't expected to be used again in the near future, so I'd leave it alone.

**Closed by samreid** 2017-04-28 19:38 UTC
Labels: status:ready-to-test, type:bug
